language: python
sudo: false
python:
  - 2.7

branches:
  only:
    master

addons:
  apt:
    packages:
    - swig
    - ccache
    - python-numpy
    - libjpeg8-dev
    - zlib1g-dev
    - libpng-dev
    - libfreetype36-dev
    - cmake
    - pillow
    - swig
    - python-qt4
    - python-qt4-gl
    - python-qt4-dev

cache:
  pip: true
  directories:
    - $HOME/.ccache

before_install:
  - ccache -s
  - export PATH=/usr/lib/ccache:${PATH}
  - pip install --upgrade pip

install:
  - pip install --upgrade -r travis-ci-requirements.txt
  - python setup.py develop
script:
  - coverage run -m haas -v
after_success:
  - coverage report
