language: python
sudo: false
python:
  - 2.7_with_system_site_packages
  - 3.4
  - 3.5

branches:
  only:
    master

addons:
  apt:
    packages:
    - swig
    - ccache
    - python-numpy
    - libjpeg8-dev
    - zlib1g-dev
    - libpng-dev
    - cmake
    - swig
    - python-qt4
    - python-qt4-gl
    - python-qt4-dev
    - graphviz

cache:
  pip: true
  directories:
    - $HOME/.ccache

before_install:
  - ccache -s
  - export PATH=/usr/lib/ccache:${PATH}
  - export ETS_TOOLKIT='qt4'
  - pip install --upgrade pip
  - if [[ ${TRAVIS_PYTHON_VERSION} == "3.4" && ${ETS_TOOLKIT} == "qt4" ]]; then ./build_pyside_wheel.sh; fi
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - pip install --upgrade -r travis-ci-requirements.txt
  - if [[ ${TRAVIS_PYTHON_VERSION} == "3.5" ]]; then pip install pyqt4; fi
  - python setup.py develop
script:
  - coverage run -m haas -v
after_success:
  - coverage report
