language: generic
sudo: false
matrix:
  include:
      - env: RUNTIME=2.7 TOOLKIT=pyqt
      - env: RUNTIME=2.7 TOOLKIT=pyside
      - env: RUNTIME=3.5 TOOLKIT=pyqt

addons:
  apt:
    packages:
    - graphviz

cache:
  pip: true
  directories:
    - $HOME/.ccache

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./travis_ci_bootstrap_edm.sh
  - edm environments create python${RUNTIME}
install:
  - edm install -e python${RUNTIME} -y networkx traits traitsui enable numpy pillow mock haas coverage ${TOOLKIT}
  - edm run -e python${RUNTIME} -- pip install pygraphviz git+http://github.com/nucleic/kiwi.git#egg=kiwisolver
  - edm run -e python${RUNTIME} -- python setup.py develop
script:
  - edm run -e python${RUNTIME} -- coverage run -m haas -v
after_success:
  - edm run -e python${RUNTIME} -- coverage report
